#!/bin/bash

X_CLASS_PATH=${CLASSPATH}

CLASSPATH=

for xfile in `echo ${X_CLASS_PATH} | tr ':' '\n'`; do
  CLASSPATH=${CLASSPATH}:$xfile
done

if [ "ts" = "ts$1" ]; then
  echo ${CLASSPATH} | tr ':' '\n'
  exit 0;
fi

export CLASSPATH

exec "$@"
