#!/bin/bash

bin=`which $0`
bin=`dirname ${bin}`
bin=`cd "$bin"; pwd`

X_CLASS_PATH=${CLASSPATH}

CLASSPATH=

for xdir in ` echo ${X_CLASS_PATH} | tr ':' '\n' `; do
  for xfile in ` ls ${xdir} `; do
    CLASSPATH=${CLASSPATH}:$xfile
  done
done

export CLASSPATH

cmd=$@
eval ${cmd}
